Insert INTO tblAnswer values (NEWID(), 'Sky Blue Crayola')
Insert INTO tblAnswer values (NEWID(), 'Purple Pizzazz')
Insert INTO tblAnswer values (NEWID(), 'Arctic Lime')
Insert INTO tblAnswer values (NEWID(), 'Tart Orange')
Insert INTO tblAnswer values (NEWID(), 'Majorelle Blue')
Insert INTO tblAnswer values (NEWID(), 'Pancakes')
Insert INTO tblAnswer values (NEWID(), 'Waffles')
Insert INTO tblAnswer values (NEWID(), 'Scrambled Eggs')
Insert INTO tblAnswer values (NEWID(), 'French Toast')
Insert INTO tblAnswer values (NEWID(), 'Oatmeal')
Insert INTO tblAnswer values (NEWID(), 'Grits')