INSERT INTO tblQuestion VALUES (NEWID(), 'What color is #51DFFF')
INSERT INTO tblQuestion VALUES (NEWID(), 'What color is #FF52DF')
INSERT INTO tblQuestion VALUES (NEWID(), 'What color is #DFFF52')
INSERT INTO tblQuestion VALUES (NEWID(), 'What color is #FF5254')
INSERT INTO tblQuestion VALUES (NEWID(), 'What color is #5254FF')