//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZJV.SurveyMaker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResponse
    {
        public System.Guid Id { get; set; }
        public System.Guid QuestionId { get; set; }
        public System.Guid AnswerId { get; set; }
        public System.DateTime ResponseDate { get; set; }
    
        public virtual tblAnswer tblAnswer { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
    }
}
